---
title: 'Data 605: Homework 10'
author: "Nick Climaco"
date: "`r Sys.Date()`"
output:
    html_document:
        highlight: pygments
        theme: cerulean
        toc: true
        toc_float: true
editor_options:
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      tidy.opts = list(width.cutoff = 80), tidy = TRUE)
```

# Exercise 1 {.tabset}

> Smith is in jail and has 1 dollar; he can get out on bail if he has 8 dollars.
A guard agrees to make a series of bets with him. If Smith bets A dollars,
he wins A dollars with probability 0.4 and loses A dollars with probability 0.6.
Find the probability that he wins 8 dollars before losing all of his money if

## Timid Strategy

> He bets 1 dollar each time

Using the equation in chp12 page 489,

$$
q_z = \frac{(q/p)^z - 1}{(q/p)^m -1}
$$
We have, 

$$
\begin{align}
z = 1 \ && p = 0.4 \\
m = 8 && q = 0.6
\end{align}
$$

Plugging them in the equation, 

$$
\Rightarrow \frac{(04./0.6)^1 - 1}{(0.4/0,6)^8 -1} = \frac{1.5 - 1}{1.5^8 -1} \approx 0.020301 \Leftrightarrow 2.03\%
$$

## Bold Strategy 

> he bets, each time, as much as possible but not more than necessary to bring his fortune up to 8 dollars

For this strategy, Smith is going to bet the as much as possible to reach $8. He starts with \$1 and he needs 3 consecutive wins. His bets would be the 1, 2, 4 and his balance would be 2,4,8 which would get him bail on the third win.

So, Smith to win 3 independent trials in a row since if he loses once he would lose all this money and the game ends.

$$
p = 0.4 \\
P(\text{Smith wins with the bold strategy}) = p * p * p = 0.4^3 = 0.064 \Leftrightarrow 6.4\%
$$

#

> Which strategy gives Smith the better chance of getting out of jail?

The bold strategy gives Smith a 6.40% change of getting out of jail compared to the timid strategy of having a 2.03% chance of getting out of jail. 
The bold strategy is also the riskier strategy because Smith can not afford to lose a single bet while the timid strategy has room to lose bets and recover those loses.
