---
title: 'Data 605: Homework 14'
author: "Nick Climaco"
date: "`r Sys.Date()`"
output:
    html_document:
        highlight: pygments
        theme: cerulean
        toc: true
        toc_float: true
editor_options:
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      tidy.opts = list(width.cutoff = 80), tidy = TRUE)
```

# Overview {.tabset}


This week, we’ll work out some Taylor Series expansions of popular functions.

•	$f (x) = \frac{1}{(1−x)}$

•	$f (x) = e^x$

•	$f (x) = ln(1 + x)$

•	$f(x)=x^{1/2}$

For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as an R- Markdown document.

## $f (x) = \frac{1}{(1−x)}$ {-}

$$
f(x) = \frac{1}{1-x} = \sum_{n=0}^{\infty} = \frac{f^n ( \alpha)}{n!} (x- \alpha) ^n \\
$$
Suppose, for simplicity, the general formula for the taylor series of f(x) centered at $\alpha = 0$ 

$$
\begin{align}
f(x) = \frac{1}{1-x},  && f(0) = 1 \\ 
f^1(x) = \frac{1}{(1-x)^2}, && f^2(0) =1 \\
f^2(x) = \frac{2}{(1-x)^3}, && f^2(0) =2 \\
f^3(x) = \frac{6}{(1-x)^4}, && f^2(0) =6 \\
f^4(x) = \frac{24}{(1-x)^5}, && f^2(0) =24 \\
\end{align}
$$

and the Taylor Series becomes, 

$$
\frac{1}{1-x} = \sum_{n=0}^\infty x^n = 1+x + x^2+ x^3+ x^4 + \ ...
$$
Now, we will use the ratio test to check for convergence

$$
\lim_{n \rightarrow 0} \Big| \frac{x^{n+1}}{x^n} \Big| = |x|
$$

So, this series converges for $|x| <1$  

For x = -1,

$$
\sum_{n=0}^\infty (-1)^n = 1 - 1+ 1 -1 + \ ... - ...
$$

neither diverges nor convergence since we dont know the nth partial sum of this series

For x = 1,

$$
\sum_{n=0}^\infty (-1)^n = 1 + 1+ 1+ \ ... - ...
$$

As n goes to infinity, it diverges to positive infinity.

So, the valid range as stated in the notes is the open interval (-1,1).

***

## $f (x) = e^x$ {-}

$$
f(x) = e^x = \sum_{n=0}^{\infty} = \frac{f^n ( \alpha)}{n!} (x- \alpha) ^n \\
$$

Suppose, for simplicity, the general formula for the taylor series of f(x) centered at $\alpha = 0$ 

$$
\begin{align}
f(x) = e^x,  && f(0) = 1 \\ 
f^1(x) = e^x, && f^2(0) =1 \\
f^2(x) = e^x, && f^2(0) =1 \\
f^3(x) = e^x, && f^2(0) =1 \\
f^4(x) = e^x, && f^2(0) =1 \\
\end{align}
$$

and the Taylor Series becomes, 

$$
e^x = \sum_{n=0}^\infty \frac{x^n}{n!} = 1+x + \frac{x^2}{2!}+ \frac{x^3}{3!}+ \frac{x^4}{4!} + \ ...
$$
Now, we will use the ratio test to check for convergence

$$
\lim_{n \rightarrow \infty} \Big| \frac{\frac{x^{n+1}}{(n+1)!}}{\frac{x^n}{n!}} \Big| = \lim_{n \rightarrow \infty} \Big| \frac{x}{n} \Big| = 0
$$

So, this series interval of convergence is $(-\infty, \infty)$

***

## $f (x) = ln(1 + x)$ {-}

$$
f(x) = ln(1+x) = \sum_{n=0}^{\infty} = \frac{f^n ( \alpha)}{n!} (x- \alpha) ^n \\
$$

Suppose, for simplicity, the general formula for the taylor series of f(x) centered at $\alpha = 0$ 

$$
\begin{align}
f(x) = ln(1+x),  && f(0) = 0 \\ 
f^1(x) = \frac{1}{(1-x)}, && f^2(0) =1 \\
f^2(x) = \frac{1}{(1-x)^2}, && f^2(0) =1 \\
f^3(x) = \frac{2}{(1-x)^3}, && f^2(0) =2 \\
f^4(x) = \frac{6}{(1-x)^4}, && f^2(0) =6 \\
\end{align}
$$

and the Taylor Series becomes, 

$$
ln(1+x) = \sum_{n=0}^\infty (-1)^n \frac{x^n}{n} = x - \frac{x^2}{2}+ \frac{x^3}{3}- \frac{x^4}{4} + \ ... \ - \ ...
$$
Now, we will use the ratio test to check for convergence

$$
\lim_{n \rightarrow \infty} \Big| \frac{(-1)^{n+1}\frac{x^{n+1}}{(n+1)}}{(-1)^n\frac{x^n}{n}} \Big| = \lim_{n \rightarrow \infty} \Big| -(x) \Big| = |x|
$$

So, this series interval of convergence is $(-1, 1)$.

## $f(x)=x^{1/2}$ {-}

$$
f(x) = x^{1/2} = \sum_{n=0}^{\infty} = \frac{f^n ( \alpha)}{n!} (x- \alpha) ^n \\
$$

Suppose, for simplicity, the general formula for the taylor series of f(x) centered at $\alpha = 0$ 

$$
\begin{align}
f(x) = x^{1/2},  && f(0) = 0 \\ 
f^1(x) = \frac{1}{2x^{1/2}}, && f^2(0) = DNE\\
f^2(x) = -\frac{1}{4x^{3/2}}, && f^2(0) =DNE \\
f^3(x) = \frac{1}{2x^{1/2}}, && f^2(0) =DNE \\
f^4(x) = -\frac{15}{16x^{7/2}}, && f^2(0) =DNE \\
\end{align}
$$

The taylor series for $f(x) = x^{1/2}$ is not defined at $\alpha = 0$ since f(x) is not differentiable at 0.